export const shellCopy = {
  brand: 'AutoServices',
  navigation: 'Navigation',
  primary: 'Primary',
  account: 'Account',
  signOut: 'Sign out',
  workspace: 'Workspace',
  overview: 'Overview',
  garage: 'Garage',
  vehicles: 'Vehicles',
  service: 'Service',
  maintenance: 'Maintenance',
  reminders: 'Reminders',
  ownership: 'Ownership',
  fuel: 'Fuel',
  expenses: 'Expenses',
  documents: 'Documents',
  reports: 'Reports',
  members: 'Members',
  settings: 'Settings',
  soon: 'Soon',
  add: 'Add',
  more: 'More',
} as const
